---
exclude: ^profiles/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/DavidAnson/markdownlint-cli2.git
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write
        language: node
        types:
          - markdown
        additional_dependencies:
          - prettier@3.5.3
