resources:
  - extensions
  - keybindings
  - settings
additionalFiles:
  - ~/.config/VSCodium/User/vsicons-custom-icons/file_type_shell_template.svg
  - ~/.config/VSCodium/User/vsicons-custom-icons/folder_type_ansible.svg
  - ~/.config/VSCodium/User/vsicons-custom-icons/folder_type_ansible_opened.svg
  - ~/.config/VSCodium/User/vsicons-custom-icons/file_type_gitleaks.svg
  - ~/.config/VSCodium/User/vsicons-custom-icons/folder_type_aptly.svg
  - ~/.config/VSCodium/User/vsicons-custom-icons/folder_type_aptly_opened.svg
  - ~/.config/VSCodium/User/vsicons-custom-icons/folder_type_systemd.svg
  - ~/.config/VSCodium/User/vsicons-custom-icons/folder_type_systemd_opened.svg
